name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  homebrew:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    if: github.repository == 'kubiks-inc/kubiks-cli'
    
    steps:
      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Calculate SHA256 checksum
        id: checksum
        run: |
          URL="https://github.com/kubiks-inc/kubiks-cli/archive/refs/tags/${{ steps.version.outputs.tag }}.tar.gz"
          SHA256=$(curl -sL "${URL}" | sha256sum | cut -d' ' -f1)
          echo "sha256=${SHA256}" >> $GITHUB_OUTPUT

      - name: Checkout homebrew-tap repository
        uses: actions/checkout@v4
        with:
          repository: kubiks-inc/homebrew-tap
          token: ${{ secrets.HOMEBREW_TOKEN }}
          path: homebrew-tap

      - name: Update formula
        run: |
          cd homebrew-tap
          
          # Update the formula file
          sed -i 's|url ".*"|url "https://github.com/kubiks-inc/kubiks-cli/archive/refs/tags/${{ steps.version.outputs.tag }}.tar.gz"|' Formula/kubiks.rb
          sed -i 's|sha256 ".*"|sha256 "${{ steps.checksum.outputs.sha256 }}"|' Formula/kubiks.rb
          sed -i 's|version ".*"|version "${{ steps.version.outputs.version }}"|' Formula/kubiks.rb

          # Commit and push changes
          git config user.name "kubiks-bot"
          git config user.email "bot@kubiks.ai"
          git add Formula/kubiks.rb
          git commit -m "Update kubiks formula to version ${{ steps.version.outputs.version }}"
          git push

      - name: Create PR for formula update
        uses: peter-evans/create-pull-request@v5
        with:
          path: homebrew-tap
          token: ${{ secrets.HOMEBREW_TOKEN }}
          commit-message: "Update kubiks formula to version ${{ steps.version.outputs.version }}"
          title: "Update kubiks formula to version ${{ steps.version.outputs.version }}"
          body: |
            Automated update of kubiks formula to version ${{ steps.version.outputs.version }}.
            
            Changes:
            - Updated download URL to point to ${{ steps.version.outputs.tag }}
            - Updated SHA256 checksum to ${{ steps.checksum.outputs.sha256 }}
            - Updated version to ${{ steps.version.outputs.version }}
            
            This PR was automatically created by the release workflow.
          branch: update-formula-${{ steps.version.outputs.version }}
          delete-branch: true